create table _user
(
    id         bigint generated by default as identity primary key,
    bio        varchar(500),
    created_at timestamp(6) with time zone not null,
    email      varchar(255),
    name       varchar(100)                not null,
    password   varchar(255)                not null,
    phone      varchar(30),
    username   varchar(50) unique          not null
);

create table chat_messages
(
    id       bigint generated by default as identity primary key,
    content  varchar(2000)               not null,
    receiver varchar(50)                 not null,
    sender   varchar(50)                 not null,
    sent_at  timestamp(6) with time zone not null
);

create index idx_msg_sender_receiver
    on chat_messages (sender, receiver, sent_at);

create index idx_msg_receiver
    on chat_messages (receiver, sent_at);