create table chat_groups
(
    id         bigint generated by default as identity primary key,
    name       varchar(100)                not null,
    created_by varchar(50)                 not null,
    created_at timestamp(6) with time zone not null
);

create table group_members
(
    group_id  bigint                      not null references chat_groups (id) on delete cascade,
    username  varchar(50)                 not null,
    joined_at timestamp(6) with time zone not null,
    primary key (group_id, username)
);

create index idx_group_members_username on group_members (username);

-- A message targets either a single user (receiver) or a group (group_id), never both.
alter table chat_messages
    alter column receiver drop not null;

alter table chat_messages
    add column group_id bigint references chat_groups (id) on delete cascade;

alter table chat_messages
    add constraint chk_msg_target check ((receiver is null) <> (group_id is null));

create index idx_msg_group on chat_messages (group_id, sent_at);
