create table chat_group
(
    id         bigint generated by default as identity primary key,
    name       varchar(100)                not null,
    created_by varchar(50)                 not null,
    created_at timestamp(6) with time zone not null
);

create table group_member
(
    group_id bigint      not null references chat_group (id) on delete cascade,
    username  varchar(50)                 not null,
    joined_at timestamp(6) with time zone not null,
    role     varchar(10) not null default 'MEMBER',
    primary key (group_id, username)
);

create index idx_group_member_username on group_member (username);
alter table group_member
    add constraint chk_group_member_role check (role in ('ADMIN', 'MEMBER'));

-- A message targets either a single user (receiver) or a group (group_id), never both.
alter table chat_message
    alter column receiver drop not null;

alter table chat_message
    add column group_id bigint references chat_group (id) on delete cascade;

alter table chat_message
    add constraint chk_msg_target check ((receiver is null) <> (group_id is null));

create index idx_msg_group on chat_message (group_id, sent_at);
